export const s: Record<string, React.CSSProperties> = {
  page: { fontFamily: 'system-ui', padding: 16, paddingBottom: 72, maxWidth: 480, margin: '0 auto', background: 'var(--tg-theme-bg-color, #fff)', color: 'var(--tg-theme-text-color, #000)', minHeight: '100vh' },
  h: { margin: '8px 0 4px' },
  sub: { margin: '2px 0', opacity: 0.8 },
  err: { color: 'red' },
  hint: { opacity: 0.7, fontSize: 14 },
  card: { border: '1px solid #ddd', borderRadius: 12, padding: 12, marginTop: 12 },
  row: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: 8, marginBottom: 8 },
  bar: { fontFamily: 'monospace' },
  btns: { display: 'flex', gap: 4, flexWrap: 'wrap' },
  btn: { minWidth: 30, height: 30, borderRadius: 8, border: '1px solid #ccc', background: '#f5f5f5' },
  btnSm: { padding: '6px 10px', borderRadius: 8, border: '1px solid #ccc', background: '#f5f5f5' },
  btnActive: { background: '#31b545', color: '#fff', borderColor: '#31b545', padding: '6px 10px', borderRadius: 8 },
  input: { width: '100%', boxSizing: 'border-box', padding: 10, borderRadius: 8, border: '1px solid #ccc', fontSize: 15 },
  inputSm: { padding: 8, borderRadius: 8, border: '1px solid #ccc', fontSize: 14, width: 130 },
  primary: { padding: '8px 14px', borderRadius: 8, border: 'none', background: '#31b545', color: '#fff', fontSize: 15 },
  danger: { padding: '8px 12px', borderRadius: 8, border: '1px solid #e5534b', background: '#fff', color: '#e5534b' },
  nav: { position: 'fixed', bottom: 0, left: 0, right: 0, display: 'flex', background: 'var(--tg-theme-bg-color, #fff)', borderTop: '1px solid #ddd', padding: '8px 4px calc(8px + env(safe-area-inset-bottom))' },
  navBtn: { flex: 1, border: 'none', background: 'none', fontSize: 13, padding: 8, opacity: 0.6 },
  navActive: { flex: 1, border: 'none', background: 'none', fontSize: 13, padding: 8, fontWeight: 700 },
}
